const RAW_WORDS: string[] = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt',
  'adult', 'after', 'again', 'agent', 'agree', 'ahead', 'alarm',
  'album', 'alert', 'alike', 'alive', 'alley', 'allow', 'alone',
  'along', 'alter', 'angel', 'angle', 'angry', 'ankle', 'apart',
  'apple', 'apply', 'arena', 'argue', 'arise', 'array', 'arrow',
  'aside', 'attic', 'audio', 'awake', 'aware', 'awful', 'basic',
  'basis', 'beach', 'beard', 'began', 'begin', 'being', 'below',
  'bench', 'black', 'blade', 'blame', 'bland', 'blank', 'blast',
  'blaze', 'bleed', 'blend', 'bless', 'blind', 'block', 'blood',
  'bloom', 'blown', 'blues', 'blunt', 'board', 'bonus', 'boost',
  'booth', 'bound', 'boxer', 'brain', 'brand', 'brave', 'break',
  'breed', 'brick', 'bride', 'brief', 'bring', 'broad', 'broke',
  'brook', 'brown', 'brush', 'budge', 'build', 'built', 'burst',
  'buyer', 'cabin', 'candy', 'carry', 'catch', 'cause', 'chain',
  'chair', 'chalk', 'chaos', 'charm', 'chase', 'cheap', 'check',
  'chess', 'chest', 'chief', 'child', 'chill', 'choir', 'chunk',
  'civic', 'civil', 'claim', 'clash', 'clasp', 'class', 'clean',
  'clear', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clock',
  'clone', 'close', 'cloth', 'cloud', 'coach', 'coast', 'comma',
  'comet', 'coral', 'could', 'count', 'court', 'cover', 'craft',
  'crane', 'crash', 'crazy', 'creek', 'crime', 'crisp', 'cross',
  'crowd', 'crown', 'cruel', 'crumb', 'crush', 'curve', 'cycle',
  'daddy', 'daily', 'dance', 'datum', 'dealt', 'death', 'debut',
  'delay', 'dense', 'depot', 'depth', 'derby', 'devil', 'dirty',
  'disco', 'ditch', 'diver', 'dizzy', 'dodge', 'dogma', 'doing',
  'donor', 'doubt', 'dough', 'draft', 'drain', 'drama', 'drank',
  'drawn', 'dream', 'dress', 'dried', 'drink', 'drive', 'drone',
  'drove', 'drums', 'dryer', 'dying', 'eager', 'early', 'earth',
  'eight', 'elite', 'empty', 'ended', 'enemy', 'enjoy', 'enter',
  'entry', 'equal', 'error', 'event', 'every', 'exact', 'exist',
  'extra', 'fable', 'faith', 'false', 'fancy', 'fatal', 'fault',
  'feast', 'fence', 'fiber', 'field', 'fifth', 'fight', 'final',
  'first', 'fixed', 'flame', 'flash', 'fleet', 'flesh', 'float',
  'flood', 'floor', 'flour', 'fluid', 'flush', 'focus', 'force',
  'forge', 'forth', 'forum', 'found', 'frame', 'frank', 'fraud',
  'fresh', 'front', 'frost', 'froze', 'fruit', 'funny', 'ghost',
  'giant', 'given', 'glass', 'globe', 'gloom', 'glory', 'gloss',
  'glove', 'going', 'grace', 'grade', 'grain', 'grand', 'grant',
  'grasp', 'grass', 'grave', 'gravy', 'graze', 'great', 'green',
  'greet', 'grief', 'grill', 'grind', 'groan', 'gross', 'group',
  'grove', 'grown', 'guard', 'guile', 'guilt', 'guise', 'gusto',
  'happy', 'harsh', 'haste', 'haven', 'heart', 'heavy', 'herbs',
  'hinge', 'hoist', 'holly', 'honey', 'honor', 'horse', 'hotel',
  'hound', 'house', 'human', 'humor', 'hurry', 'hyper', 'ideal',
  'image', 'imply', 'index', 'infer', 'inner', 'input', 'irony',
  'issue', 'ivory', 'japan', 'jelly', 'jewel', 'joker', 'judge',
  'juice', 'juicy', 'jumbo', 'knack', 'kneel', 'knife', 'knock',
  'known', 'lapse', 'laser', 'laugh', 'layer', 'learn', 'lease',
  'leash', 'least', 'leave', 'legal', 'lemon', 'level', 'light',
  'limit', 'linen', 'liner', 'liver', 'local', 'lodge', 'logic',
  'loose', 'lover', 'lower', 'lucky', 'lunch', 'lying', 'magic',
  'major', 'maker', 'manor', 'maple', 'march', 'marks', 'match',
  'mayor', 'media', 'mercy', 'merit', 'metal', 'might', 'minor',
  'minus', 'mixer', 'model', 'money', 'month', 'moral', 'motor',
  'mourn', 'mouth', 'movie', 'muddy', 'music', 'nasal', 'naval',
  'nerve', 'never', 'newly', 'night', 'ninja', 'noise', 'north',
  'noted', 'novel', 'nurse', 'nymph', 'occur', 'ocean', 'offer',
  'often', 'olive', 'onset', 'opera', 'order', 'ought', 'outer',
  'oxide', 'ozone', 'paint', 'panel', 'panic', 'paper', 'party',
  'pasta', 'patch', 'pause', 'peace', 'peach', 'pearl', 'pedal',
  'penny', 'perch', 'petty', 'phase', 'phone', 'photo', 'piano',
  'piece', 'pilot', 'pinch', 'pixel', 'pizza', 'place', 'plain',
  'plane', 'plant', 'plate', 'plaza', 'plead', 'pluck', 'plumb',
  'plume', 'plump', 'point', 'polar', 'polka', 'porch', 'power',
  'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize',
  'probe', 'prone', 'proof', 'proud', 'prune', 'psalm', 'pulse',
  'punch', 'pupil', 'purse', 'queen', 'query', 'quest', 'queue',
  'quick', 'quiet', 'quota', 'quote', 'radar', 'radio', 'rainy',
  'raise', 'range', 'rapid', 'ratio', 'reach', 'ready', 'realm',
  'rebel', 'refer', 'reign', 'relax', 'reply', 'rider', 'ridge',
  'rifle', 'right', 'risky', 'rival', 'river', 'robot', 'rocky',
  'rouge', 'rough', 'round', 'route', 'royal', 'rugby', 'ruler',
  'rural', 'sadly', 'saint', 'salad', 'sauce', 'scale', 'scary',
  'scene', 'scope', 'score', 'scout', 'sense', 'setup', 'seven',
  'shade', 'shake', 'shall', 'shame', 'shape', 'share', 'shark',
  'sharp', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt',
  'shock', 'shoot', 'short', 'shout', 'shove', 'shown', 'sight',
  'silly', 'since', 'sixth', 'sixty', 'skill', 'skull', 'skunk',
  'slant', 'slash', 'slave', 'sleep', 'sleet', 'slept', 'slide',
  'slime', 'sloth', 'slump', 'small', 'smart', 'smell', 'smile',
  'smoke', 'snack', 'snake', 'sneak', 'solid', 'solve', 'sorry',
  'south', 'space', 'spare', 'spark', 'spawn', 'speak', 'spear',
  'speed', 'spend', 'spice', 'spike', 'spine', 'spite', 'split',
  'spoke', 'spook', 'spoon', 'sport', 'spray', 'squad', 'staff',
  'stage', 'stain', 'stair', 'stake', 'stale', 'stalk', 'stall',
  'stamp', 'stand', 'stark', 'start', 'state', 'stays', 'steak',
  'steal', 'steam', 'steel', 'steep', 'steer', 'stern', 'stick',
  'stiff', 'still', 'stomp', 'stone', 'stood', 'stool', 'store',
  'storm', 'story', 'stove', 'strap', 'straw', 'stray', 'strip',
  'stuck', 'study', 'stuff', 'style', 'sugar', 'suite', 'sunny',
  'super', 'surge', 'swamp', 'swear', 'sweet', 'swept', 'swift',
  'swing', 'sword', 'swore', 'sworn', 'syrup', 'table', 'taken',
  'taste', 'teach', 'tears', 'tense', 'tenth', 'terms', 'terse',
  'thank', 'theme', 'there', 'these', 'thick', 'thing', 'think',
  'third', 'those', 'three', 'threw', 'throw', 'thumb', 'tiger',
  'timed', 'timer', 'tired', 'title', 'today', 'token', 'totem',
  'touch', 'tough', 'tower', 'toxic', 'trace', 'track', 'trade',
  'trail', 'train', 'trait', 'tramp', 'trash', 'trawl', 'treat',
  'trend', 'tribe', 'trick', 'tried', 'troop', 'trout', 'truck',
  'truly', 'tryst', 'tumor', 'tuner', 'tunic', 'twice', 'twist',
  'typed', 'ulcer', 'ultra', 'under', 'union', 'unity', 'until',
  'upper', 'upset', 'urban', 'usage', 'usher', 'usual', 'utter',
  'valid', 'value', 'valve', 'vapor', 'vault', 'video', 'vigor',
  'vinyl', 'viral', 'virus', 'visit', 'visor', 'vista', 'vital',
  'vivid', 'voice', 'voter', 'waltz', 'waste', 'watch', 'water',
  'weary', 'weave', 'wedge', 'weird', 'wheat', 'wheel', 'where',
  'which', 'while', 'white', 'whole', 'wider', 'widow', 'wield',
  'witch', 'woman', 'world', 'worry', 'worst', 'worth', 'would',
  'wound', 'wrath', 'write', 'wrong', 'yacht', 'yield', 'young',
  'youth', 'zebra', 'zones', 'zippy',
];

/** O(1) lookup set — the only data structure needed for word validation. */
export const VALID_WORDS: Set<string> = new Set(RAW_WORDS.map(w => w.toUpperCase()));

export function isValidWord(word: string): boolean {
  return VALID_WORDS.has(word.toUpperCase());
}

export function pickRandomWord(): string {
  const words = [...VALID_WORDS];
  const idx = Math.floor(Math.random() * words.length);
  return words[idx] ?? words[0] ?? 'CRANE';
}
